spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springbook?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&serverTimezone=Asia/Seoul
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
